//var xhr = new XMLHttpRequest();
// var po = new XMLHttpRequest();
// po.open("POST", url, true);
// po = JSON.stringifyl(po);
// po.setRequeestHeader("Content-Type","application/x-www-form-urlencoded;charset=UTF-8");
// po.send();

// xhr.onreadystatechange = handleStateChange; // Implemented elsewhere.
// xhr.open("GET", url, true);
// xhr = JSON.stringify(xhr);
// xhr.send();
// var data = xhr.responseText;
// var data = JSON.parse(xhr.responseText);

//url : 接口地址

function ajax_method(url,data,method,success) {
    // 异步对象
    var ajax = new XMLHttpRequest();

    // get 跟post  需要分别写不同的代码
    if (method=='get') {
        // get请求
        if (data) {
            // 如果有值
            url+='?';
            url+=data;
        }else{

        }
        // 设置 方法 以及 url
        ajax.open(method,url);

        // send即可
        ajax.send();
    }else{
        // post请求
        // post请求 url 是不需要改变
        ajax.open(method,url);

        // 需要设置请求报文
        ajax.setRequestHeader("Content-type","application/x-www-form-urlencoded");

        // 判断data send发送数据
        if (data) {
            // 如果有值 从send发送
            ajax.send(data);
        }else{
            // 木有值 直接发送即可
            ajax.send();
        }
    }

    // 注册事件
    ajax.onreadystatechange = function () {
        // 在事件中 获取数据 并修改界面显示
        if (ajax.readyState==4&&ajax.status==200) {
            // console.log(ajax.responseText);

            // 将 数据 让 外面可以使用
            // return ajax.responseText;

            // 当 onreadystatechange 调用时 说明 数据回来了
            // ajax.responseText;

            // 如果说 外面可以传入一个 function 作为参数 success
            success(ajax.responseText);
        }
    }

}
//collection
//让他给我要，其他名字
//url 是属性的key
//url是object的property
//
// ajax_method(collection,{"url":window.location.href},'post', (res)=> {
//     const images = document.querySelectorAll('img');
//     for (let i = 0; i < images.length; i++) {
//         for (let u = 0; u < res.length; u++) {
//             if (images[i].src.includes(res[u])) {
//                 images[i].src = '';
//             }
//         }
        
//     }   
// })


let arr = [
    "jigaboo",
    "mound of venus",
    "asslover",
    "queaf",
    "whitetrash",
    "meatrack",
    "urine",
    "randy",
    "herpes",
    "niglet",
    "narcotic",
    "pudboy",
    "rimming",
    "boner",
    "pornography",
    "poop chute",
    "israel",
    "slanteye",
    "muffdiving",
    "jiggabo",
    "assassination",
    "peepshpw",
    "popimp",
    "girl on",
    "testicles",
    "molestor",
    "peni5",
    "tranny",
    "barface",
    "arsehole",
    "pissed",
    "sixsixsix",
    "execute",
    "shitty ",
    "conspiracy",
    "hamas",
    "cunilingus",
    "bitcher",
    "muslim",
    "niggled",
    "muffindiver",
    "cocksman",
    "aroused",
    "niggling",
    "fingerfucker ",
    "nlggor",
    "niggaz",
    "assfuck",
    "slant",
    "urinate",
    "mothafucked ",
    "fungus",
    "retard",
    "gummer",
    "venus mound",
    "spaghettinigger",
    "mickeyfinn",
    "fuckers",
    "jizzim",
    "tramp",
    "quashie",
    "prince albert piercing",
    "hardon",
    "menage a trois",
    "bukkake",
    "australian",
    "raped",
    "buggery",
    "weenie",
    "lickme",
    "reverse cowgirl",
    "tonguetramp",
    "copulate",
    "schlong",
    "damnit",
    "crackpipe",
    "buttmuncher",
    "cameltoe",
    "camgirl",
    "hotpussy",
    "cuntfucker",
    "slave",
    "sluts",
    "ball licking",
    "hentai",
    "jackshit",
    "dickman",
    "doo-doo",
    "crimes",
    "shitdick",
    "slapper",
    "urinary",
    "tantra",
    "nookie",
    "fuckedup",
    "gubba",
    "niggur",
    "cybersex",
    "dicklicker",
    "cunillingus",
    "hitlerism",
    "triplex",
    "busty",
    "dicklick",
    "kunilingus",
    "asian",
    "tonguethrust",
    "fistfucking ",
    "assmonkey",
    "criminal",
    "cockknob",
    "children's",
    "footfucker",
    "blonde action",
    "spitter",
    "weapon",
    "cuntlicking ",
    "sexy-slim",
    "lemon party",
    "vibrater",
    "upskirt",
    "jijjiboo",
    "fuckfriend",
    "mothafucka",
    "sniggered",
    "buttfuckers",
    "nutfucker",
    "peehole",
    "taboo",
    "erection",
    "nudity",
    "lesbayn",
    "hummer",
    "shortfuck",
    "cherrypopper",
    "adult",
    "palestinian",
    "pussylips",
    "nooner",
    "how to kill",
    "blumpkin",
    "stiffy",
    "piss pig",
    "beastiality",
    "latin",
    "butchbabes",
    "spunk",
    "gross",
    "crackwhore",
    "butt-fuckers",
    "kraut",
    "pooping",
    "style doggy",
    "lactate",
    "fecal",
    "rusty trombone",
    "wrinkled starfish",
    "spigotty",
    "clogwog",
    "whitey",
    "radical",
    "slaughter",
    "bollick",
    "sodomite",
    "balls",
    "nimphomania",
    "ball gag",
    "muff diver",
    "jail bait",
    "beaver",
    "asspirate",
    "bareback",
    "pimpjuice",
    "ballsack",
    "bi-sexual",
    "torture",
    "limey",
    "nookey",
    "breastman",
    "loser",
    "kills",
    "lesbo",
    "beatyourmeat",
    "lovemaking",
    "clitoris",
    "fornicate",
    "wet dream",
    "double penetration",
    "missionary position",
    "bugger",
    "lovejuice",
    "date rape",
    "eatballs",
    "handjob",
    "nlgger",
    "dixiedyke",
    "junglebunny",
    "sonofabitch",
    "goddamned",
    "deep throat",
    "assclown",
    "shitforbrains",
    "screwyou",
    "ethiopian",
    "nastyslut",
    "gang bang",
    "lubejob",
    "tied up",
    "make me come",
    "rimjob",
    "sexfarm",
    "tight white",
    "lezbe",
    "lezbo",
    "tribadism",
    "butt-bang",
    "asskiss",
    "sadism",
    "biteme",
    "angie",
    "abortion",
    "murderer",
    "motherfucker",
    "sextoy",
    "doggy style",
    "cunntt",
    "cooly",
    "ball sack",
    "sodom",
    "slideitin",
    "fudge packer",
    "fatfuck",
    "communist",
    "felatio ",
    "libido",
    "cuntfuck",
    "niggardly",
    "fuckface",
    "faggot",
    "protestant",
    "trailertrash",
    "headfuck",
    "dickweed",
    "refugee",
    "trannie",
    "giant cock",
    "sexhound",
    "titlover",
    "moslem",
    "krappy",
    "black cock",
    "idiot",
    "tortur",
    "erotic",
    "donkey punch",
    "dirty pillows",
    "cockcowboy",
    "sucker",
    "cocktail",
    "hymen",
    "terrorist",
    "mufflikcer",
    "phonesex",
    "teste",
    "pisshead",
    "slime",
    "brea5t",
    "tea bagging",
    "slutt",
    "cumbubble",
    "blackout",
    "hijacking",
    "premature",
    "sextogo",
    "racist",
    "jimfish",
    "flydye",
    "juggs",
    "wigger",
    "niggard's",
    "devilworshipper",
    "firing",
    "gatorbait",
    "murder",
    "chinese",
    "fastfuck",
    "bastinado",
    "kondum",
    "pansy",
    "destroy",
    "women rapping",
    "titfucker",
    "crime",
    "swinger",
    "shitola",
    "killer",
    "booby",
    "pimpsimp",
    "strap on",
    "zigabo",
    "faith",
    "bisexual",
    "gangsta",
    "boobies",
    "kafir",
    "dp action",
    "husky",
    "homoerotic",
    "twinkie",
    "spooge",
    "sleezebag",
    "slutwhore",
    "dickless",
    "cumfest",
    "israeli",
    "niggardliness",
    "goddamit",
    "sandnigger",
    "insest",
    "foreskin",
    "acrotomophilia",
    "dumbbitch",
    "fuckmonkey",
    "pubiclice",
    "cyberslimer",
    "titfuck",
    "cummer",
    "kumquat",
    "one guy one jar",
    "carruth",
    "cocktease",
    "trisexual",
    "rabbi",
    "cunnilingus",
    "dipshit",
    "welfare",
    "arabs",
    "transvestite",
    "penile",
    "mothafuckings",
    "peckerwood",
    "enemy",
    "negroid",
    "genital",
    "gangbanger",
    "queef",
    "strapon",
    "thicklips",
    "female squirting",
    "flydie",
    "crabs",
    "christ",
    "ejaculate",
    "carpet muncher",
    "lucifer",
    "butchdyke",
    "vatican",
    "skumbag",
    "horseshit",
    "eunuch",
    "dickforbrains",
    "bondage",
    "kumbullbe",
    "crack",
    "niggerhole",
    "niggard",
    "rosy palm",
    "assranger",
    "beat-off",
    "bastard ",
    "asspuppies",
    "jiggerboo",
    "cuntlick ",
    "pommie",
    "doggie style",
    "jesuschrist",
    "feltch",
    "chode",
    "pleasure chest",
    "wetback",
    "zipperhead",
    "necro",
    "goddamnmuthafucker",
    "whiskeydick",
    "slopy",
    "executioner",
    "colored",
    "ethnic",
    "turnon",
    "nofuckingway",
    "mastrabator",
    "jack off",
    "orgies",
    "pisses ",
    "blow j",
    "criminals",
    "cockqueen",
    "tosser",
    "snownigger",
    "holestuffer",
    "dipstick",
    "nipplering",
    "minority",
    "italiano",
    "palesimian",
    "genitals",
    "conservative",
    "jebus",
    "bullcrap",
    "cumqueen",
    "spread legs",
    "cancer",
    "kaffir",
    "mocky",
    "suckmytit",
    "vorarephilia",
    "naked",
    "shited",
    "spermhearder",
    "whore",
    "african",
    "disease",
    "lovebone",
    "spreadeagle",
    "coprolagnia",
    "humping",
    "suicide girls",
    "pole smoker",
    "shrimping",
    "purinapricness",
    "sexslave",
    "big knockers",
    "iblowu",
    "pissin ",
    "skank",
    "lotion",
    "asshole",
    "easyslut",
    "mothafucker",
    "cocksucked ",
    "hosejob",
    "wanker",
    "cumjockey",
    "eat my ass",
    "lovegoo",
    "whites",
    "propaganda",
    "sexwhore",
    "welcher",
    "how to murder",
    "phuked",
    "suckoff",
    "shithapens",
    "auto erotic",
    "sultry women",
    "barenaked",
    "wetspot",
    "sixtynine",
    "wrapping men",
    "buttplug",
    "jiggy",
    "alligatorbait",
    "flange",
    "shitfit",
    "dirty",
    "huge fat",
    "bulldyke",
    "orgasm",
    "bumfuck",
    "deposit",
    "big breasts",
    "sexual",
    "japanese",
    "suckmyass",
    "church",
    "goyim",
    "bohunk",
    "bigass",
    "fannyfucker",
    "gaymuthafuckinwhore",
    "babies",
    "girls",
    "fuck buttons",
    "fagging",
    "pisser",
    "sandm",
    "escort",
    "octopussy",
    "tinkle",
    "snigger",
    "vibrator",
    "swalow",
    "niggles",
    "asslicker",
    "molester",
    "backseat",
    "seppo",
    "sexually",
    "boong",
    "voyeur",
    "butthole",
    "hoser",
    "asswhore",
    "cocaine",
    "skanky",
    "european",
    "mothafuck",
    "titlicker",
    "buttstain",
    "penises",
    "spermacide",
    "mexican",
    "skankybitch",
    "white power",
    "puddboy",
    "coondog",
    "stripclub",
    "mockie",
    "american",
    "jesus",
    "tushy",
    "kumbubble",
    "mormon",
    "ontherag",
    "henhouse",
    "slutty",
    "big black",
    "daterape",
    "phukked",
    "cuntlicker ",
    "failed",
    "lezbefriends",
    "pissing",
    "bitchy",
    "kigger",
    "nastywhore",
    "bangbros",
    "upthebutt",
    "cohee",
    "fistfuck",
    "fuckingbitch",
    "shibari",
    "jiggaboo",
    "japcrap",
    "raper",
    "jackass",
    "orgasim ",
    "sexed",
    "jackoff",
    "baby batter",
    "toilet",
    "tampon",
    "snowballing",
    "goldenshower",
    "titties",
    "towelhead",
    "titjob",
    "molestation",
    "crapola",
    "foursome",
    "suicide",
    "scrotum",
    "cumming",
    "niggerhead",
    "pussie",
    "abuse",
    "analannie",
    "cocksucking",
    "breastjob",
    "blonde on blonde action",
    "paedophile",
    "kumming",
    "reestie",
    "suckme",
    "willie",
    "shhit",
    "titbitnipply",
    "hot chick",
    "skankwhore",
    "fudgepacker",
    "dragqueen",
    "deapthroat",
    "barelylegal",
    "circlejerk",
    "shinola",
    "hookers",
    "flatulence",
    "mafia",
    "gokkun",
    "argie",
    "buttpirate",
    "goregasm",
    "fagot",
    "redneck",
    "cockhead",
    "freakfuck",
    "2 girls 1 cup",
    "crotchjockey",
    "dripdick",
    "fuckina",
    "phungky",
    "beaver cleaver",
    "darky",
    "magicwand",
    "screw",
    "dominatrix",
    "butt-fucker",
    "neonazi",
    "fuckpig",
    "manpaste",
    "molest",
    "whiskydick",
    "darkie",
    "rearend",
    "niggardliness's",
    "trojan",
    "smack",
    "lapdance",
    "brunette action",
    "hindoo",
    "fourtwenty",
    "deepthroat",
    "moles",
    "pommy",
    "fuckher",
    "stringer",
    "one cup two girls",
    "backdoorman",
    "male squirting",
    "shiting",
    "clamdiver",
    "fairy",
    "pussylicker",
    "nigre",
    "robber",
    "horny",
    "penetration",
    "phuking",
    "cigarette",
    "dyefly",
    "playboy",
    "golden shower",
    "cumshot",
    "chinamen",
    "pickaninny",
    "diddle",
    "fatah",
    "bombers",
    "suckdick",
    "bigbastard",
    "mosshead",
    "pornking",
    "terror",
    "pimper",
    "fuckbuddy",
    "period",
    "catholics",
    "pistol",
    "g-spot",
    "doodoo",
    "mockey",
    "funeral",
    "prickhead",
    "allah",
    "pussyeater",
    "cocksmith",
    "executed",
    "barely legal",
    "niggarding",
    "swastika",
    "buried",
    "pocho",
    "weewee",
    "whiskey",
    "beast",
    "phone sex",
    "muncher",
    "fuckhead",
    "smackthemonkey",
    "badfuck",
    "harem",
    "nigerians",
    "bastardo",
    "shooting",
    "pissoff ",
    "fistfucked ",
    "ginzo",
    "mattressprincess",
    "primetime",
    "undressing",
    "fuckable",
    "damnation",
    "stroking",
    "leather restraint",
    "yankee",
    "beastality",
    "cocksucer",
    "goddamn",
    "poopchute",
    "shitfaced",
    "dickhead",
    "gangbanged ",
    "masterbate",
    "pikey",
    "rosy palm and her 5 sisters",
    "doggiestyle",
    "bitches",
    "desire",
    "pansies",
    "dickbrain",
    "sissy",
    "felch",
    "penis",
    "horney",
    "buttmunch",
    "baptist",
    "assassin",
    "fingering",
    "osama",
    "mothafucking ",
    "republican",
    "freefuck",
    "goatse",
    "transexual",
    "bunghole",
    "assholes",
    "butt-fuck",
    "nig nog",
    "snowback",
    "sniper",
    "gangbang",
    "cockfight",
    "death",
    "mggor",
    "skankbitch",
    "masturbate",
    "usama",
    "babeland",
    "dickwad",
    "cornhole",
    "nigra",
    "fuckinright",
    "blue waffle",
    "niggle",
    "timbernigger",
    "picaninny",
    "whorefucker",
    "yellowman",
    "dommes",
    "lolita",
    "grostulation",
    "dixiedike",
    "shitfucker",
    "hymie",
    "sheeney",
    "asswipe",
    "crash",
    "vomit",
    "femdom",
    "cameljockey",
    "footfuck",
    "sonofbitch",
    "cleveland steamer",
    "dahmer",
    "feltcher",
    "bitch",
    "fingerfuckers",
    "buttface",
    "dammit",
    "lovepistol",
    "twink",
    "shitting",
    "blind",
    "reefer",
    "beaver lips",
    "motherlovebone",
    "panties",
    "fucka",
    "fatass",
    "lugan",
    "devil",
    "pornflick",
    "russkie",
    "fight",
    "thirdleg",
    "jerk off",
    "negroes",
    "moron",
    "shaved beaver",
    "gonzagas",
    "drunken",
    "blackman",
    "asskisser",
    "crotchrot",
    "motherfuckin",
    "lezzo",
    "fondle",
    "slopey",
    "clusterfuck",
    "fister",
    "skankfuck",
    "condom",
    "shithouse",
    "cockblock",
    "horniest",
    "facefucker",
    "assmuncher",
    "bollock",
    "stupidfuck",
    "assmunch",
    "prostitute",
    "poorwhitetrash",
    "honkey",
    "farting ",
    "getiton",
    "bulldike",
    "raping",
    "futanari",
    "nigger",
    "illegal",
    "hardcore",
    "skinflute",
    "throating",
    "asspacker",
    "leather straight jacket",
    "raghead",
    "crotch",
    "goo girl",
    "knobbing",
    "buttman",
    "glazeddonut",
    "urethra play",
    "africa",
    "fairies",
    "fuckmehard",
    "shaved pussy",
    "bitchin",
    "cocks",
    "fucker",
    "gyppie",
    "kinkster",
    "penthouse",
    "biatch",
    "erect",
    "shitfull",
    "vaginal",
    "fraud",
    "color",
    "flasher",
    "filipino",
    "sexpot",
    "sexymoma",
    "boonie",
    "buttcheeks",
    "cacker",
    "shemale",
    "porchmonkey",
    "violet blue",
    "eatme",
    "looser",
    "virgin",
    "assbagger",
    "negro's",
    "lesbian",
    "hustler",
    "cunteyed",
    "tarbaby",
    "nipples",
    "dumbfuck",
    "backdoor",
    "wuzzie",
    "sadom",
    "threeway",
    "pimpjuic",
    "chinaman",
    "brown showers",
    "pubes",
    "masturbating",
    "bollocks",
    "bunga",
    "sodomize",
    "goddammit",
    "footstar",
    "goatcx",
    "chink",
    "butthead",
    "liquor",
    "spermbag",
    "jailbait",
    "beatoff",
    "incest",
    "vagina",
    "urophilia",
    "niggarded",
    "kaffer",
    "rearentry",
    "motherfucking",
    "areola",
    "harder",
    "greaseball",
    "loverocket",
    "asshore",
    "fingerfood",
    "shaggin",
    "commie",
    "hitler",
    "honky",
    "tongue",
    "fubar",
    "dildo",
    "sniggering",
    "omorashi",
    "pedophile",
    "freakyfucker",
    "swallower",
    "birdlock",
    "bigbutt",
    "nastyho",
    "goddamnes",
    "pooperscooper",
    "sucks",
    "nambla",
    "puntang",
    "gay sex",
    "bootycall",
    "reject",
    "enema",
    "spankthemonkey",
    "buggered",
    "jewish",
    "asslick",
    "bitching",
    "strip club",
    "gringo",
    "pendy",
    "boody",
    "chocolate rosebuds",
    "buttfuck",
    "domination",
    "faeces",
    "splittail",
    "clamdigger",
    "shitlist",
    "double dong",
    "niggor",
    "motherfucked",
    "slimeball",
    "pedobear",
    "excrement",
    "goddamnit",
    "stagg",
    "hijack",
    "sexkitten",
    "coolie",
    "servant",
    "gyppo",
    "slopehead",
    "fingerfuck ",
    "dumbass",
    "williewanker",
    "fisting",
    "crapper",
    "sixtyniner",
    "fetish",
    "two girls one cup",
    "threesome",
    "bitchez",
    "manhater",
    "nympho",
    "mothafuckin",
    "shitted",
    "hitlerist",
    "semen",
    "scissoring",
    "sodomise",
    "big tits",
    "muffdiver",
    "farty ",
    "nsfw images",
    "ecchi",
    "dirty sanchez",
    "mooncricket",
    "shite",
    "asshat",
    "intercourse",
    "intheass",
    "jacktheripper",
    "felcher",
    "spaghettibender",
    "angry",
    "gaysex ",
    "willy",
    "addict",
    "russki",
    "slimebucket",
    "bogan",
    "goodpoop",
    "fuckme ",
    "shitcan",
    "brothel",
    "rentafuck",
    "footjob",
    "shitoutofluck",
    "licker",
    "nigerian",
    "pindick",
    "cockrider",
    "felching",
    "geezer",
    "balllicker",
    "ponyplay",
    "fuckoff",
    "jizzum",
    "sadis",
    "hodgie",
    "fatfucker",
    "bicurious",
    "bombs",
    "mr hands",
    "bi curious",
    "sooty",
    "liberal",
    "prick",
    "clover clamps",
    "spunky",
    "nymphomania",
    "playgirl",
    "vietcong",
    "yellow showers",
    "pecker",
    "bitchslap",
    "demon",
    "jihad",
    "assjockey",
    "macaca",
    "kinky",
    "pooper",
    "homicide",
    "fuuck",
    "shitfuck",
    "tittie",
    "wanking",
    "girl on top",
    "fistfucker ",
    "zoophilia",
    "farted ",
    "nigglings",
    "hiscock",
    "erotism",
    "honger",
    "beaner",
    "kummer",
    "whash",
    "fuckinnuts",
    "fuckin",
    "tainted love",
    "kotex",
    "poverty",
    "butchdike",
    "datnigga",
    "uterus",
    "execution",
    "trots",
    "luckycammeltoe",
    "roach",
    "swallow",
    "motherfuck",
    "ball gravy",
    "slutwear",
    "panti",
    "kissass",
    "shawtypimp",
    "muffdive",
    "mulatto",
    "noonan",
    "banging",
    "tunneloflove",
    "doggystyle",
    "fuckwhore",
    "rapist",
    "homobangers",
    "porno",
    "barfface",
    "syphilis",
    "pearlnecklace",
    "sleezeball",
    "sextoys",
    "assman",
    "german",
    "shagging",
    "anilingus",
    "stupidfucker",
    "loadedgun",
    "beastial",
    "shithead",
    "asses",
    "pussylover",
    "niggah",
    "gotohell",
    "jigga",
    "remains",
    "frotting",
    "thirdeye",
    "fuckknob",
    "inthebuff",
    "nawashi",
    "roundeye",
    "retarded",
    "mastabate",
    "disturbed",
    "kunnilingus",
    "bung hole",
    "pee-pee",
    "camwhore",
    "satan",
    "lowlife",
    "tubgirl",
    "fucks",
    "diseases",
    "blow your l",
    "addicts",
    "snatchpatch",
    "poontang",
    "snatch",
    "pussypounder",
    "knife",
    "pu55i",
    "footaction",
    "footlicker",
    "bimbos",
    "mothafuckaz",
    "pussycat",
    "fucking",
    "funfuck",
    "piece of shit",
    "boang",
    "nipple",
    "fuckit",
    "shoot",
    "booty call",
    "slutting",
    "coitus",
    "spermherder",
    "raging boner",
    "buttfucker",
    "quickie",
    "grope",
    "rectum",
    "kanake",
    "soviet",
    "honkers",
    "chinky",
    "dingleberry",
    "shota",
    "hillbillies",
    "godammit",
    "fugly",
    "nasty",
    "ejaculation",
    "waysted",
    "carpetmuncher",
    "nastybitch",
    "camel toe",
    "strappado",
    "limpdick",
    "heroin",
    "panty",
    "polack",
    "pornprincess",
    "gonorrehea",
    "meatbeatter",
    "crotchmonkey",
    "topless",
    "shithappens",
    "foot fetish",
    "canadian",
    "amateur",
    "whitenigger",
    "niger",
    "bigger",
    "squaw",
    "hand job",
    "buttbang",
    "titty",
    "defecate",
    "niggaracci",
    "pussyfucker",
    "corruption",
    "girls gone wild",
    "boobs",
    "ejaculated",
    "shitface",
    "autoerotic",
    "creamy",
    "bible",
    "fckcum",
    "knockers",
    "fucck",
    "whorehouse",
    "cocksmoker",
    "queer",
    "cocklover",
    "assblaster",
    "bombing",
    "hooters",
    "forni",
    "bazooms",
    "vulva",
    "failure",
    "racial",
    "fuckfreak",
    "cuntsucker",
    "fingerfucked ",
    "scallywag",
    "mastabater",
    "byatch",
    "whigger",
    "pussy",
    "group sex",
    "attack",
    "fucktard",
    "marijuana",
    "filipina",
    "asscowboy",
    "fatso",
    "bazongas",
    "chickslick",
    "joint",
    "niggards",
    "cockblocker",
    "lingerie",
    "headlights",
    "pegging",
    "kaffre",
    "taste my",
    "crack-whore",
    "lynch",
    "tub girl",
    "bullshit",
    "explosion",
    "black",
    "homosexual",
    "fucked",
    "showtime",
    "lesbin",
    "fellatio",
    "nudger",
    "women's",
    "boonga",
    "choad",
    "assault",
    "cra5h",
    "tuckahoe",
    "fingerfucking ",
    "hijacker",
    "athletesfoot",
    "livesex",
    "hostage",
    "cocknob",
    "hard core",
    "fuckbag",
    "stupid",
    "radicals",
    "figging",
    "fuckfest",
    "hottotrot",
    "kinbaku",
    "sexhouse",
    "violet wand",
    "analsex",
    "nigga",
    "nittit",
    "suckmydick",
    "pussies",
    "hotdamn",
    "assfucker",
    "jizim",
    "pixie",
    "cemetery",
    "rigger",
    "ethical slut",
    "dolcett",
    "ejaculating ",
    "cumquat",
    "eatpussy",
    "givehead",
    "drunk",
    "phukking",
    "shiteater",
    "catholic",
    "hooker",
    "cocksuck ",
    "cocksucker",
    "ball kicking",
    "fuckyou",
    "crappy",
    "feltching",
    "mideast",
    "ecstacy",
    "ribbed",
    "dog style",
    "interracial",
    "tongue in a",
    "pocha",
    "skankywhore",
    "pu55y",
    "motherfuckings",
    "piker",
    "peepshow",
    "yiffy",
    "tongethruster",
    "nigger's",
    "breastlover",
    "stroke",
    "twobitwhore",
    "shits",
    "israel's",
    "jerkoff",
    "bullet vibe",
    "assassinate",
    "killed",
    "pocketpool",
    "whacker",
    "juggalo",
    "negro",
    "spick",
    "gyppy",
    "nymph",
    "snigger's",
    "violence",
    "lovemuscle",
    "feces",
    "booty",
    "niggers",
    "shitter",
    "sodomy",
    "hussy",
    "pisspig",
    "coprophilia",
    "christian",
    "pimped",
    "breast",
    "sperm",
    "coloured",
    "redlight",
    "blacks",
    "bumblefuck",
    "slavedriver",
    "killing",
    "uptheass",
    "bestial",
    "sweetness",
    "piccaninny",
    "jizjuice",
    "nignog",
    "mgger",
    "sexing",
    "virginbreaker",
    "samckdaddy",
    "masterblaster",
    "heterosexual",
    "jigger ",
    "blowjob",
    "lovegun",
    "shitstain",
    "spank",
    "lesbain",
    "sniggers",
    "jizm ",
    "testicle",
    "ball sucking",
    "dragqween",
    "pubic",
    "titfuckin",
    "moneyshot",
    "camslut",
    "bountybar",
    "assklown",
    "cocky",
    "transsexual",
    "unfuckable",
    "bestiality",
    "cocklicker",
];
const text = document.querySelectorAll('h1, h2, h3, h4, h5, p, li, td, caption, span, a,div')
    for (let u = 0; u < arr.length; u++) {
        let wrongW = arr[u];
        for (let i = 0; i < text.length; i++) {
            if (text[i].innerHTML.includes(wrongW) && !(text[i].innerHTML.includes("<"))) {
                // let thistext = text[i].innerHTML;
                // let str='';//拼text显示的内容
                // let num=getCharCount(thistext,wrongW);
                // let start=0;//记录当前下标位置
                // for(let i=0;i<num;i++){
                //     let index = thistext.indexOf(wrongW); // 字符第一次出现的位置
                //     index=thistext.indexOf(wrongW,index+i);//当前位置
                //     str+=thistext.substr(start, index-start)
                //         +"\n<span style='display:inline;background: red!important' class='heise' title=\"Big brother is watching you\">" + wrongW + "</span>";
                //     start=index+wrongW.length;
                // }
                // str+=thistext.substr(start);
                text[i].classList.add('heise');
                // text[i].innerHTML =str;
            }
        }
    }



// for (let i = 1; i < arr.length; i++ ){
//     let wrongW = arr[i];
//     const text = document.querySelectorAll('h1, h2, h3, h4, h5, p, li, td, caption, span, a,div')
//     console.log(music);
//     for (let i=0; i < text.length; i++) {
//         console.log(text[i].innerHTML);
//         console.log(text[i].innerHTML.includes(wrongW) && !(text[i].innerHTML.includes("<")));
//         if (text[i].innerHTML.includes(wrongW) && !(text[i].innerHTML.includes("<"))) {
//             text[i].innerHTML = "\n<span class='heise' title=\"Big brother is watching you\">" + text[i].innerHTML + "</span>";
//             console.log(text[i].innerHTML)
//         }
//     }
// }